### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by amotl**
Hey @huw ,

thanks for this nice Discourse add-on!

We added some log messages and slightly improved robustness and error handling. Also, the path to the configuration file is now obtained as argument from the command line.

With kind regards,
Andreas.

### CODE REVIEW

**Comment by huw** [comment]
Merged, and published to npm 👍 

I made a slight change to maintain backward compatibility, by setting `config.json` as the default argument. Since I'm using semver this is now 1.1.0.

Also, would you be interested in push access? It looks like your org might be using this into the future, and seem more interested in maintaining it than me. Let me know!

**Comment by amotl** [comment]
Hi @huw , thanks for the quick merge. We are happy to accept your offer for having push access, however we can not commit ourselves to long term maintenance, as we already have some stuff out there to care about.

As we learned, making the http request does not work synchronously yet as intended, as it seems to be difficult to achieve within Nodejs, obviously :-). We'll see if we can add more improvements if it starts getting too annoying in daily use. We might create an issue reflecting this on GitHub, if you don't mind.

Thanks again for accepting our PR!

**Comment by huw** [comment]
I've added you as a contributor, is there anyone else from your org who might be interested? No qualms if you can't contribute, I'd rather you add to it unhindered if you can. Let me know when you push changes though so I can publish to npm—and if your changes interfere with backward compatibility please submit a PR instead for approval.

All good :smile:

**Comment by amotl** [comment]
Hey @huw , please also add @einsiedlerkrebs. Thanks a bunch and all the best, Andreas.

**Pull request merged**
